### ISSUE TITLE
Global Illumination effects

### ISSUE THREAD

**Issue by hedvigjosefin** [lindacnatt/DayVSNight#11]
- [x] Ambient Occlusion via Lightmapping Settings in Lighting tab
- [x] distribute Lightmaps (apply Indirect Illumination), Light probes (apply Realtime light)
- [x]  Lighting -real-time
- [x] Indirect Illumination baked via Mixed Lighting / Baked Indirect GI in Lighting tab for lightmaps

Ambient occlusion can be augmented more specifically by altering its code file

See https://docs.unity3d.com/Manual/GIIntro.html and
https://learn.unity.com/tutorial/introduction-to-lighting-and-rendering

**Comment by lindacnatt** [comment]
https://www.youtube.com/watch?v=VnG2gOKV9dw

Nice tutorial!
